#!/bin/sh
set -e

LLVM_STAGING=${LLVM_STAGING:-"/build/llvm-staging"}

cd ${LLVM_STAGING}/llvm-project && git checkout main && \
  lbh repo && \
  cd ${LLVM_STAGING}/build/default && \
  lbh dev \
      --monorepo ${LLVM_STAGING}/llvm-project \
      --build_dir $PWD \
      --build_runtimes \
      --config_only && \
  ninja && ninja check-all check-runtimes && \
  rm -rf ${LLVM_STAGING}/build/bootstrap/* && \
  cd ${LLVM_STAGING}/build/bootstrap && \
  lbh dev \
      --monorepo ${LLVM_STAGING}/llvm-project \
      --build_dir $PWD \
      --clang ../default/bin/clang \
      --lld ../default/bin/ld.lld \
      --build_runtimes \
      --config_only && \
  ninja clean && ninja && \
  ninja check-all check-runtimes
