#!/bin/sh
set -e

LLVM_STAGING=${LLVM_STAGING:-"/build/llvm-staging"}

cd ${LLVM_STAGING}/llvm-project && git checkout main && \
    lbh repo && \
    cd ${LLVM_STAGING}/build/default && \
    ninja && ninja check-all && \
    rm -rf ${LLVM_STAGING}/build/bootstrap/* && \
    cd ${LLVM_STAGING}/build/bootstrap && \
    lbh dev --install_prefix /opt/clang-nightly \
                            --monorepo ${LLVM_STAGING}/llvm-project \
                            --build_dir $PWD \
                            --clang ../default/bin/clang \
                            --lld $(which ld) \
                            --build_llvm_runtimes \
                            --build_polly \
                            --use_malloc mimalloc \
                            --config_only && \
    ninja clean && ninja && \
    ninja check-all && \
    cpack -G TXZ -D CPACK_THREADS=$(nproc)
