#!/bin/sh
set -e

LLVM_STAGING=${LLVM_STAGING:-"/build/llvm-staging"}

mkdir -p ${LLVM_STAGING}/build/sanitizers
cd ${LLVM_STAGING}/build/sanitizers && \
  env BUILDBOT_MONO_REPO_PATH="${LLVM_STAGING}/llvm-project" \
      ${LLVM_STAGING}/llvm-zorg/zorg/buildbot/builders/sanitizers/buildbot_fast.sh
