#!/bin/bash
cd /opt/clang/bin
ln -sfn clang llvm-clang
ln -sfn clang++ llvm-clang++
cat > llvm-clang.cfg << EOF
-pipe
--ld-path=/opt/clang/bin/ld.lld
-L/opt/clang/lib
-Wl,-rpath,/opt/clang/lib
-rtlib=compiler-rt
-unwindlib=libunwind
EOF
cat > llvm-clang++.cfg << EOF
-pipe
--ld-path=/opt/clang/bin/ld.lld
-nostdinc++
-nostdlib++
-isystem /opt/clang/include/c++/v1
-L/opt/clang/lib
-Wl,-rpath,/opt/clang/lib
-rtlib=compiler-rt
-unwindlib=libunwind
-stdlib=libc++
-Wl,-as-needed
-lc++
-Wl,-no-as-needed
EOF
