#!/bin/bash
PREFIX=${PREFIX:-"/opt/clang"}
cd ${PREFIX}/bin
ln -sfn clang llvm-clang
ln -sfn clang++ llvm-clang++
cat > llvm-clang.cfg << EOF
-pipe
--ld-path=${PREFIX}/bin/ld.lld
-L${PREFIX}/lib
-Wl,-rpath,${PREFIX}/lib
-rtlib=compiler-rt
-unwindlib=libunwind
EOF
cat > llvm-clang++.cfg << EOF
-pipe
--ld-path=${PREFIX}/bin/ld.lld
-nostdinc++
-nostdlib++
-isystem ${PREFIX}/include/c++/v1
-L${PREFIX}/lib
-Wl,-rpath,${PREFIX}/lib
-rtlib=compiler-rt
-unwindlib=libunwind
-stdlib=libc++
-Wl,-as-needed
-lc++
-Wl,-no-as-needed
EOF
