#!/bin/bash
set -e

export https_proxy="socks5://localhost:1080"

LLVM_DEV=${LLVM_DEV:-"${HOME}/llvm-dev"}

cd ${LLVM_DEV} && git clone --bare https://github.com/llvm/llvm-project.git && \
    git clone --single-branch -l llvm-project.git llvm-project

cd ${LLVM_DEV} && git clone --bare https://github.com/llvm/llvm-test-suite.git && \
    git clone --single-branch -l llvm-test-suite.git llvm-test-suite
