#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Build helper for LLVM project.

import os
import sys
import argparse
import subprocess
import shutil
import shlex
import logging
import time


def CPack(path, num_threads=1):
    cpack = shutil.which('cpack')
    if not cpack:
        logging.info("Can't find cpack in the system, won't pack.")
        return err
    cpack_cmd = [
        cpack,
        '-G',
        'TXZ',
        '-D',
        'CPACK_THREADS={}'.format(num_threads),
    ]
    cp = subprocess.run(cpack_cmd, cwd=path)
    if cp.returncode != 0:
        logging.error("Can't pack with {}".format(cpack_cmd))
    return cp.returncode


class Builder(object):
    def __init__(self,
                 monorepo=None,
                 build_dir=None,
                 install_prefix=None,
                 cmake=shutil.which('cmake'),
                 ninja=shutil.which('ninja'),
                 build_type='Release',
                 cc=None,
                 ld=None,
                 cflags=[],
                 cxxflags=[],
                 projects=[],
                 runtimes=[],
                 extra_cmake_flags=[],
                 config_only=False,
                 njobs=os.cpu_count(),
                 ninja_targets=[]):
        assert monorepo
        assert build_dir
        assert install_prefix
        self.cmake = cmake
        self.ninja = ninja
        self.monorepo = os.path.abspath(monorepo)
        self.build_dir = os.path.abspath(build_dir)
        self.install_prefix = os.path.abspath(install_prefix)
        self.cc = os.path.abspath(cc) if cc else None
        self.ld = os.path.abspath(ld) if ld else None
        self.cflags = cflags
        self.cxxflags = cxxflags
        self.projects = projects
        self.runtimes = runtimes
        self.extra_cmake_flags = extra_cmake_flags
        self.ninja_targets = ninja_targets
        self.build_type = build_type
        self.config_only = config_only
        self.njobs = njobs

    def BuildCMakeCommand(self):
        cmake_command = [
            self.cmake,
            '-GNinja',
            '-DCMAKE_MAKE_PROGRAM={}'.format(self.ninja),
            '-DLLVM_ENABLE_ASSERTIONS=On',
            '-DCMAKE_BUILD_TYPE={}'.format(self.build_type),
            '-DCMAKE_INSTALL_PREFIX={}'.format(self.install_prefix),
        ]
        if self.cc:
            cmake_command.append('-DCMAKE_C_COMPILER={}'.format(self.cc))
        if self.ld:
            cmake_command.append('-DLLVM_USE_LINKER={}'.format(self.ld))
        if self.cflags:
            cmake_command.append('-DCMAKE_C_FLAGS={}'.format(
                shlex.join(self.cflags)))
        if self.cxxflags:
            cmake_command.append('-DCMAKE_CXX_FLAGS={}'.format(
                shlex.join(self.cxxflags)))
        if self.projects:
            cmake_command.append('-DLLVM_ENABLE_PROJECTS={}'.format(';'.join(
                self.projects)))
        if self.runtimes:
            cmake_command.append('-DLLVM_ENABLE_RUNTIMES={}'.format(';'.join(
                self.runtimes)))
        cmake_command.extend(self.extra_cmake_flags)
        return cmake_command

    # Implicitly reset runtimes.
    def ConfigAndBuildProjects(self):
        self.runtimes = []
        return self.ConfigAndBuild()

    # Implicitly reset projects.
    def ConfigAndBuildRuntimes(self):
        self.projects = []
        err = self.config(os.path.join(self.monorepo, 'runtimes'),
                          self.build_dir)
        if err != 0:
            return err
        return self.Build()

    def config(self, src_dir, build_dir):
        cmake_command = self.BuildCMakeCommand()
        cmake_command.extend(['-S', src_dir])
        cmake_command.extend(['-B', build_dir])
        err = subprocess.call(cmake_command)
        if err != 0:
            logging.error('cmake failed: {}'.format(cmake_command))
        return err

    def ConfigAndBuild(self):
        err = self.Config()
        if self.config_only or err != 0:
            return err
        return self.Build()

    def Config(self):
        return self.config(os.path.join(self.monorepo, 'llvm'), self.build_dir)

    def Build(self):
        ninja_command = [
            self.ninja,
            '-j%d' % self.njobs,
        ]
        ninja_command.extend(self.ninja_targets)
        err = subprocess.call(ninja_command, cwd=self.build_dir)
        if err != 0:
            logging.error('ninja failed: {}'.format(ninja_command))
        return err


def AddCommonArguments(parser):
    parser.add_argument('--enable_timer', default=False, action='store_true')
    parser.add_argument('--cmake_binary', default=shutil.which('cmake'))
    parser.add_argument('--ninja_binary', default=shutil.which('ninja'))
    parser.add_argument('--config_only', action='store_true', default=False)
    parser.add_argument('--install_prefix', required=True)
    parser.add_argument('--monorepo', required=True)
    parser.add_argument('--build_dir', required=True)
    parser.add_argument('-j', dest='njobs', type=int, default=os.cpu_count())


def BuildProduct(config):
    extra_cmake_flags = []
    if config.dylib:
        extra_cmake_flags.append('-DLLVM_LINK_LLVM_DYLIB=ON')
    if config.binutils_include:
        extra_cmake_flags.append('-DLLVM_BINUTILS_INCDIR={path}'.format(
            path=config.binutils_include))
    if config.use_newpm:
        extra_cmake_flags.append('-DLLVM_USE_NEWPM=On')
    if config.llvm_toolchain:
        # All in llvm's toolchain.
        extra_cmake_flags.append('-DCLANG_DEFAULT_PIE_ON_LINUX=ON')
        extra_cmake_flags.append('-DCLANG_DEFAULT_LINKER=lld')
        extra_cmake_flags.append('-DCLANG_DEFAULT_RTLIB=compiler-rt')
        extra_cmake_flags.append('-DCLANG_DEFAULT_UNWINDLIB=libunwind')
        extra_cmake_flags.append('-DCLANG_DEFAULT_CXX_STDLIB=libc++')
        extra_cmake_flags.append('-DCLANG_DEFAULT_OBJCOPY=llvm-objcopy')
        extra_cmake_flags.append('-DCLANG_DEFAULT_OPENMP_RUNTIME=libomp')
        extra_cmake_flags.append('-DLIBCXX_USE_COMPILER_RT=ON')
        extra_cmake_flags.append('-DLIBCXXABI_USE_COMPILER_RT=ON')
        extra_cmake_flags.append('-DLIBUNWIND_USE_COMPILER_RT=ON')
        extra_cmake_flags.append('-DLIBCXXABI_USE_LLVM_UNWINDER=ON')
    # FIXUP openmp.
    extra_cmake_flags.append('-DLIBOMP_LIBFLAGS=-lm')
    extra_cmake_flags.append('-DOPENMP_ENABLE_LIBOMPTARGET=OFF')
    # Use at risk, since atomic in compiler-rt will be statically linked against.
    if config.enable_atomic:
        extra_cmake_flags.append('-DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=NO')
    if config.lto:
        extra_cmake_flags.append('-DLLVM_ENABLE_LTO=Thin')
    cflags = ['-pipe']
    cxxflags = cflags['-pipe']
    if config.native:
        cflags.append('-march=native')
        cxxflags.append('-march=native')
    builder = Builder(config.monorepo,
                      config.build_dir,
                      config.install_prefix,
                      cc=config.clang,
                      cflags=['-pipe'],
                      cxxflags=['-pipe'],
                      ld=config.lld,
                      config_only=config.config_only,
                      extra_cmake_flags=extra_cmake_flags,
                      njobs=config.njobs)
    builder.runtimes = []
    if config.minimal:
        builder.projects = [
            'clang',
            'clang-tools-extra',
            'lld',
            'compiler-rt',
        ]
    else:
        builder.projects = [
            'clang',
            'clang-tools-extra',
            'lld',
            'lldb',
            'mlir',
            'polly',
            'compiler-rt',
            'libcxx',
            'libcxxabi',
            'libunwind',
            'openmp',
        ]
    err = builder.Config()
    if err != 0:
        return err
    err = builder.Build()
    if err != 0:
        return err
    return CPack(config.build_dir, config.njobs)


def BuildForDev(options):
    build_type = 'Release'
    if options.debug:
        build_type = 'RelWithDebInfo'
    extra_cmake_flags = []
    if options.build_shared_libs:
        extra_cmake_flags.append('-DLLVM_BUILD_LLVM_DYLIB=On')
    extra_cmake_flags.append('-DLLVM_PARALLEL_LINK_JOBS=3')
    builder = Builder(options.monorepo,
                      options.build_dir,
                      options.install_prefix,
                      build_type=build_type,
                      cc=options.clang,
                      ld=options.lld,
                      cflags=['-pipe'],
                      cxxflags=['-pipe'],
                      extra_cmake_flags=extra_cmake_flags,
                      config_only=options.config_only,
                      projects=[
                          'clang',
                          'compiler-rt',
                          'lld',
                      ])
    return builder.ConfigAndBuild()


def BootstrapMinimal(config):
    stage1_path = os.path.join(os.path.abspath(config.build_dir), 'stage1')
    stage2_path = os.path.join(os.path.abspath(config.build_dir), 'stage2')
    os.makedirs(stage1_path, exist_ok=True)
    os.makedirs(stage2_path, exist_ok=True)
    # Stage1.
    stage1_builder = Builder(config.monorepo,
                             stage1_path,
                             config.install_prefix,
                             cc=config.bootstrap_cc,
                             ld=config.bootstrap_ld,
                             cflags=['-pipe'],
                             cxxflags=['-pipe'],
                             projects=['clang', 'lld'],
                             njobs=config.njobs)
    err = stage1_builder.ConfigAndBuild()
    if err != 0:
        logging.error('Stage1 failed.')
        return err
    if config.skip_stage2:
        return CPack(stage1_path, config.njobs)
    stage2_builder = Builder(config.monorepo,
                             stage2_path,
                             config.install_prefix,
                             cc=os.path.join(stage1_path, 'bin', 'clang'),
                             cflags=['-pipe'],
                             cxxflags=['-pipe'],
                             ld=os.path.join(stage1_path, 'bin', 'ld.lld'),
                             projects=[
                                 'clang',
                                 'lld',
                                 'clang-tools-extra',
                             ],
                             runtimes=['compiler-rt'],
                             njobs=config.njobs)
    err = stage2_builder.ConfigAndBuild()
    if err != 0:
        logging.error('Stage2 failed.')
        return err
    if not config.skip_stage2_test:
        stage2_builder.ninja_targets = ['check-all']
        err = stage2_builder.Build()
        if err != 0:
            logging.error('Stage2 test failed.')
            return err
    return CPack(stage2_path, config.njobs)


def BuildWithPGOAndLTO(config):
    # TODO: Use llvm/utils/collect_and_build_with_pgo.py to profile.
    llvm_bin_dir = os.path.join(config.llvm_path, 'bin')

    def FindTool(name):
        return shutil.which(name, path=llvm_bin_dir)

    profiling_pass_path = os.path.join(config.build_dir, 'profiling-pass')
    lto_pass_path = os.path.join(config.build_dir, 'lto-pass')
    os.makedirs(profiling_pass_path, exist_ok=True)
    os.makedirs(lto_pass_path, exist_ok=True)
    # LTO pass.
    lto_pass_extra_cmake_flags = ['-DLLVM_ENABLE_LTO=Thin']
    lto_pass_builder = Builder(config.monorepo,
                               lto_pass_path,
                               config.install_prefix,
                               cc=FindTool('clang'),
                               ld=FindTool('ld.lld'),
                               config_only=config.config_only,
                               runtimes=[
                                   'compiler-rt',
                               ],
                               projects=[
                                   'clang',
                                   'lld',
                                   'clang-tools-extra',
                               ],
                               extra_cmake_flags=lto_pass_extra_cmake_flags,
                               njobs=config.njobs)
    err = lto_pass_builder.ConfigAndBuild()
    if err != 0:
        logging.error('LTO pass failed.')
        return err
    return CPack(lto_pass_path, config.njobs)


def main():
    parser = argparse.ArgumentParser(
        description='Build Clang/LLVM under different mode.')
    subparsers = parser.add_subparsers(dest='subcmd')

    # Bootstrap build.
    bootstrap_minimal = subparsers.add_parser(
        'bootstrap_minimal',
        description='Bootstrap a minimal Clang/LLVM toolchain.')
    AddCommonArguments(bootstrap_minimal)
    bootstrap_minimal.add_argument('--bootstrap_cc',
                                   default=shutil.which('gcc'))
    bootstrap_minimal.add_argument('--bootstrap_ld',
                                   default=shutil.which('ld'))
    bootstrap_minimal.add_argument('--skip_stage2',
                                   default=False,
                                   action='store_true')
    bootstrap_minimal.add_argument('--skip_stage2_test',
                                   action='store_true',
                                   default=False)
    bootstrap_minimal.set_defaults(func=BootstrapMinimal)

    # Dev build.
    dev = subparsers.add_parser('dev',
                                description='Build Clang/LLVM for developing.')
    AddCommonArguments(dev)
    dev.add_argument('--clang', default=shutil.which('clang'))
    dev.add_argument('--lld', default=shutil.which('ld.lld'))
    dev.add_argument('--debug', action='store_true', default=False)
    dev.add_argument('--build_shared_libs', action='store_true', default=False)
    dev.set_defaults(func=BuildForDev)

    # Prod build.
    prod = subparsers.add_parser(
        'prod', description='Build Clang/LLVM toolchain as product.')
    # See https://clang.llvm.org/docs/Toolchain.html.
    prod.add_argument('--clang', default=shutil.which('clang'))
    prod.add_argument('--lld', default=shutil.which('ld.lld'))
    prod.add_argument('--llvm_toolchain', action='store_true', default=False)
    prod.add_argument('--minimal', action='store_true', default=False)
    prod.add_argument('--use_newpm', action='store_true', default=False)
    prod.add_argument('--enable_atomic', action='store_true', default=False)
    prod.add_argument('--lto', action='store_true', default=False)
    prod.add_argument('--native', action='store_true', default=False)
    prod.add_argument('--dylib', action='store_true', default=False)
    prod.add_argument('--binutils_include')
    AddCommonArguments(prod)
    prod.set_defaults(func=BuildProduct)

    # PGO/LTO build.
    opt = subparsers.add_parser(
        'opt', description='Build PGO/LTOed Clang/LLVM toolchain.')
    AddCommonArguments(opt)
    opt.add_argument('--llvm_path', required=True)
    opt.add_argument('--native', action='store_true', default=False)
    opt.add_argument('--skip_profiling_pass',
                     action='store_true',
                     default=False)
    opt.add_argument('--llvm_test_suite_path')
    opt.set_defaults(func=BuildWithPGOAndLTO)

    config = parser.parse_args()
    if not config.subcmd:
        parser.print_help()
        return -1
    start = time.perf_counter()
    err = config.func(config)
    end = time.perf_counter()
    if config.enable_timer:
        print('Time elapsed: {}'.format(end - start))
    return err


if __name__ == '__main__':
    sys.exit(main())
