#!/bin/sh
# Press meta key to present all windows.
kwriteconfig5 --file ~/.config/kwinrc --group ModifierOnlyShortcuts --key Meta \
              "org.kde.kglobalaccel,/component/kwin,org.kde.kglobalaccel.Component,invokeShortcut,ExposeAll"
qdbus org.kde.KWin /KWin reconfigure
