#!/bin/bash

set -e

LLVM_SRC=${LLVM_SRC:-"/build/llvm-dev/llvm-project"}
REV=${1:-main}
COMMITISH="llvmorg-${REV}"
if [[ ${REV} =~ "main" ]]; then
  COMMITISH="main"
fi

export XZ_OPT='-T0'
# Please ensure `tar.xz.command`` is configured by
# `git config tar.xz.command "xz -z -T0"` or
# `git config --global tar.xz.command "xz -z -T0"``

cd ${LLVM_SRC} && \
  git archive -o "/build/llvm-${REV}.tar.xz" \
      "${COMMITISH}" --prefix="llvm-${REV}/"
