#!/bin/bash

set -e

LLVM_SRC=${LLVM_SRC:-"/build/llvm-dev/llvm-project"}
REV=${1:-main}
COMMITISH="llvmorg-${REV}"
if [[ ${REV} =~ "main" ]]; then
  COMMITISH="main"
fi

# Please ensure `tar.zstd.command`` is configured by
# `git config tar.zstd.command "zstd -T0"` or
# `git config --global tar.zstd.command "zstd -T0"``

cd ${LLVM_SRC} && \
  git archive -o "/build/llvm-${REV}.tar.zstd" \
      "${COMMITISH}" --prefix="llvm-${REV}/"
