#!/bin/bash

set -e

LLVM_DEV=${LLVM_DEV:-"/build/llvm-dev/llvm-project"}
REV=${1:-main}
COMMITISH="llvmorg-${REV}"
if [[ ${REV} =~ "main" ]]; then
  COMMITISH="main"
fi

cd ${LLVM_DEV} && \
  git archive -o "/build/llvm-${REV}.tar.xz" \
      "${COMMITISH}" --prefix="llvm-${REV}/"
