# Includes one of the default files in src/bootstrap/defaults
profile = "user"
changelog-seen = 2

[llvm]
assertions = true
static-libstdcpp = false
targets = "X86;AArch64;RISCV;PowerPC"
use-linker = 'lld'

[build]
docs = false

[rust]
default-linker = '/usr/local/bin/mold'
lld = true
use-lld = true
jemalloc = true
debug = true
debuginfo-level = 2

[target.x86_64-unknown-linux-gnu]
cc = '/usr/bin/clang'
cxx = '/usr/bin/clang++'
ar = '/usr/bin/llvm-ar'
ranlib = '/usr/bin/llvm-ranlib'
linker = '/usr/bin/clang'

[dist]
compression-formats = ['xz']
